apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: grafana-postgresql-datasource
    access: proxy
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: smartbuilding
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
    isDefault: true
    editable: false
